### ISSUE TITLE
HTTPS URLs for submodules?

### ISSUE THREAD

**Issue by david-oswald** [stacksmashing/pdnd-example#2]
Hi,

Thanks for this really nice project? The submodule here currently uses ssh, which is fine when you've an SSH key (added to the Github profile) on the dev machine, but sometimes this might not be the case - could be changed to use https instead?

See also: https://github.com/stacksmashing/pdnd-picoprobe/issues/1

**Comment by nezza** [comment]
Done, sorry somehow missed this :(
